server {
    listen 3001;
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback - sve rute vracaju index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # CORS headers za lokalni razvoj
    add_header Access-Control-Allow-Origin *;
}
