# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x04task\"Z\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\x12\x11\n\tcompleted\x18\x05 \x01(\x08\"H\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\"\x1c\n\x0eGetTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"!\n\x13\x43ompleteTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"(\n\x0cTaskResponse\x12\x18\n\x04task\x18\x01 \x01(\x0b\x32\n.task.Task\"%\n\x08TaskList\x12\x19\n\x05tasks\x18\x01 \x03(\x0b\x32\n.task.Task\"\x07\n\x05\x45mpty2\xe6\x01\n\x0bTaskService\x12\x39\n\nCreateTask\x12\x17.task.CreateTaskRequest\x1a\x12.task.TaskResponse\x12\x33\n\x07GetTask\x12\x14.task.GetTaskRequest\x1a\x12.task.TaskResponse\x12(\n\tListTasks\x12\x0b.task.Empty\x1a\x0e.task.TaskList\x12=\n\x0c\x43ompleteTask\x12\x19.task.CompleteTaskRequest\x1a\x12.task.TaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=20
  _globals['_TASK']._serialized_end=110
  _globals['_CREATETASKREQUEST']._serialized_start=112
  _globals['_CREATETASKREQUEST']._serialized_end=184
  _globals['_GETTASKREQUEST']._serialized_start=186
  _globals['_GETTASKREQUEST']._serialized_end=214
  _globals['_COMPLETETASKREQUEST']._serialized_start=216
  _globals['_COMPLETETASKREQUEST']._serialized_end=249
  _globals['_TASKRESPONSE']._serialized_start=251
  _globals['_TASKRESPONSE']._serialized_end=291
  _globals['_TASKLIST']._serialized_start=293
  _globals['_TASKLIST']._serialized_end=330
  _globals['_EMPTY']._serialized_start=332
  _globals['_EMPTY']._serialized_end=339
  _globals['_TASKSERVICE']._serialized_start=342
  _globals['_TASKSERVICE']._serialized_end=572
# @@protoc_insertion_point(module_scope)
