server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/users/ {
    proxy_pass http://uporabniki:8000/;
  }

  location /api/projects/ {
    proxy_pass http://projekti:3000/;
  }

  location /api/tasks/ {
    proxy_pass http://naloge:5001/;
  }
}
