name: Tests
on: [push]

jobs:
  test-user:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r uporabniki/requirements.txt

      - name: Run user tests
        run: pytest uporabniki/tests
        env:
          PYTHONPATH: uporabniki
    
  test-task:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install deps
        run: |
          pip install -r naloge/requirements.txt

      - name: Run task tests
        run: pytest